include_fragments = true

accept = ["200..=299", "401", "403"]

exclude = [
    "https://slack.com/help/articles/8328303095443-Understand-Channel-Managers-in-Slack",
    "https://observe2020.io",
    "https://servicenow.com",
    "https://sched.co",
    "https://srecon19emea.sched.com",
    # excluding links to user profiles is done for performance
    # because there are a lot of links to user profiles in this repository
    # and GitHub extra throttles access to user profile pages
    "^https://github.com/[^/]+$",
]

# Retry configuration with more reasonable timeout values
max_retries = 3
# Wait time (in seconds) between retries with exponential backoff
retry_wait_time = 1
# Reduce number of concurrent requests to avoid triggering rate limits
max_concurrency = 75
